import { TimeZone } from "@/api/services/tendiflow/types/timezone";
import { SelectOptionType } from "@/types/general";

export const TIMEZONE_OPTIONS: SelectOptionType[] = [
  // Africa
  { name: "Africa/Abidjan", value: TimeZone.AFRICA_ABIDJAN },
  { name: "Africa/Accra", value: TimeZone.AFRICA_ACCRA },
  { name: "Africa/Addis_Ababa", value: TimeZone.AFRICA_ADDIS_ABABA },
  { name: "Africa/Algiers", value: TimeZone.AFRICA_ALGIERS },
  { name: "Africa/Asmara", value: TimeZone.AFRICA_ASMARA },
  { name: "Africa/Bamako", value: TimeZone.AFRICA_BAMAKO },
  { name: "Africa/Bangui", value: TimeZone.AFRICA_BANGUI },
  { name: "Africa/Banjul", value: TimeZone.AFRICA_BANJUL },
  { name: "Africa/Bissau", value: TimeZone.AFRICA_BISSAU },
  { name: "Africa/Blantyre", value: TimeZone.AFRICA_BLANTYRE },
  { name: "Africa/Brazzaville", value: TimeZone.AFRICA_BRAZZAVILLE },
  { name: "Africa/Bujumbura", value: TimeZone.AFRICA_BUJUMBURA },
  { name: "Africa/Cairo", value: TimeZone.AFRICA_CAIRO },
  { name: "Africa/Casablanca", value: TimeZone.AFRICA_CASABLANCA },
  { name: "Africa/Ceuta", value: TimeZone.AFRICA_CEUTA },
  { name: "Africa/Conakry", value: TimeZone.AFRICA_CONAKRY },
  { name: "Africa/Dakar", value: TimeZone.AFRICA_DAKAR },
  { name: "Africa/Dar_es_Salaam", value: TimeZone.AFRICA_DAR_ES_SALAAM },
  { name: "Africa/Djibouti", value: TimeZone.AFRICA_DJIBOUTI },
  { name: "Africa/Douala", value: TimeZone.AFRICA_DOUALA },
  { name: "Africa/El_Aaiun", value: TimeZone.AFRICA_EL_AAIUN },
  { name: "Africa/Freetown", value: TimeZone.AFRICA_FREETOWN },
  { name: "Africa/Gaborone", value: TimeZone.AFRICA_GABORONE },
  { name: "Africa/Harare", value: TimeZone.AFRICA_HARARE },
  { name: "Africa/Johannesburg", value: TimeZone.AFRICA_JOHANNESBURG },
  { name: "Africa/Juba", value: TimeZone.AFRICA_JUBA },
  { name: "Africa/Kampala", value: TimeZone.AFRICA_KAMPALA },
  { name: "Africa/Khartoum", value: TimeZone.AFRICA_KHARTOUM },
  { name: "Africa/Kigali", value: TimeZone.AFRICA_KIGALI },
  { name: "Africa/Kinshasa", value: TimeZone.AFRICA_KINSHASA },
  { name: "Africa/Lagos", value: TimeZone.AFRICA_LAGOS },
  { name: "Africa/Libreville", value: TimeZone.AFRICA_LIBREVILLE },
  { name: "Africa/Lome", value: TimeZone.AFRICA_LOME },
  { name: "Africa/Luanda", value: TimeZone.AFRICA_LUANDA },
  { name: "Africa/Lubumbashi", value: TimeZone.AFRICA_LUBUMBASHI },
  { name: "Africa/Lusaka", value: TimeZone.AFRICA_LUSAKA },
  { name: "Africa/Malabo", value: TimeZone.AFRICA_MALABO },
  { name: "Africa/Maputo", value: TimeZone.AFRICA_MAPUTO },
  { name: "Africa/Maseru", value: TimeZone.AFRICA_MASERU },
  { name: "Africa/Mbabane", value: TimeZone.AFRICA_MBABANE },
  { name: "Africa/Mogadishu", value: TimeZone.AFRICA_MOGADISHU },
  { name: "Africa/Monrovia", value: TimeZone.AFRICA_MONROVIA },
  { name: "Africa/Nairobi", value: TimeZone.AFRICA_NAIROBI },
  { name: "Africa/Ndjamena", value: TimeZone.AFRICA_NDJAMENA },
  { name: "Africa/Niamey", value: TimeZone.AFRICA_NIAMEY },
  { name: "Africa/Nouakchott", value: TimeZone.AFRICA_NOUAKCHOTT },
  { name: "Africa/Ouagadougou", value: TimeZone.AFRICA_OUAGADOUGOU },
  { name: "Africa/Porto-Novo", value: TimeZone.AFRICA_PORTO_NOVO },
  { name: "Africa/Sao_Tome", value: TimeZone.AFRICA_SAO_TOME },
  { name: "Africa/Tripoli", value: TimeZone.AFRICA_TRIPOLI },
  { name: "Africa/Tunis", value: TimeZone.AFRICA_TUNIS },
  { name: "Africa/Windhoek", value: TimeZone.AFRICA_WINDHOEK },

  // America
  { name: "America/Adak", value: TimeZone.AMERICA_ADAK },
  { name: "America/Anchorage", value: TimeZone.AMERICA_ANCHORAGE },
  { name: "America/Anguilla", value: TimeZone.AMERICA_ANGUILLA },
  { name: "America/Antigua", value: TimeZone.AMERICA_ANTIGUA },
  { name: "America/Araguaina", value: TimeZone.AMERICA_ARAGUAINA },
  {
    name: "America/Argentina/Buenos_Aires",
    value: TimeZone.AMERICA_ARGENTINA_BUENOS_AIRES,
  },
  {
    name: "America/Argentina/Catamarca",
    value: TimeZone.AMERICA_ARGENTINA_CATAMARCA,
  },
  {
    name: "America/Argentina/Cordoba",
    value: TimeZone.AMERICA_ARGENTINA_CORDOBA,
  },
  { name: "America/Argentina/Jujuy", value: TimeZone.AMERICA_ARGENTINA_JUJUY },
  {
    name: "America/Argentina/La_Rioja",
    value: TimeZone.AMERICA_ARGENTINA_LA_RIOJA,
  },
  {
    name: "America/Argentina/Mendoza",
    value: TimeZone.AMERICA_ARGENTINA_MENDOZA,
  },
  {
    name: "America/Argentina/Rio_Gallegos",
    value: TimeZone.AMERICA_ARGENTINA_RIO_GALLEGOS,
  },
  { name: "America/Argentina/Salta", value: TimeZone.AMERICA_ARGENTINA_SALTA },
  {
    name: "America/Argentina/San_Juan",
    value: TimeZone.AMERICA_ARGENTINA_SAN_JUAN,
  },
  {
    name: "America/Argentina/San_Luis",
    value: TimeZone.AMERICA_ARGENTINA_SAN_LUIS,
  },
  {
    name: "America/Argentina/Tucuman",
    value: TimeZone.AMERICA_ARGENTINA_TUCUMAN,
  },
  {
    name: "America/Argentina/Ushuaia",
    value: TimeZone.AMERICA_ARGENTINA_USHUAIA,
  },
  { name: "America/Aruba", value: TimeZone.AMERICA_ARUBA },
  { name: "America/Asuncion", value: TimeZone.AMERICA_ASUNCION },
  { name: "America/Atikokan", value: TimeZone.AMERICA_ATIKOKAN },
  { name: "America/Bahia", value: TimeZone.AMERICA_BAHIA },
  { name: "America/Bahia_Banderas", value: TimeZone.AMERICA_BAHIA_BANDERAS },
  { name: "America/Barbados", value: TimeZone.AMERICA_BARBADOS },
  { name: "America/Belem", value: TimeZone.AMERICA_BELEM },
  { name: "America/Belize", value: TimeZone.AMERICA_BELIZE },
  { name: "America/Blanc-Sablon", value: TimeZone.AMERICA_BLANC_SABLON },
  { name: "America/Boa_Vista", value: TimeZone.AMERICA_BOA_VISTA },
  { name: "America/Bogota", value: TimeZone.AMERICA_BOGOTA },
  { name: "America/Boise", value: TimeZone.AMERICA_BOISE },
  { name: "America/Cambridge_Bay", value: TimeZone.AMERICA_CAMBRIDGE_BAY },
  { name: "America/Campo_Grande", value: TimeZone.AMERICA_CAMPO_GRANDE },
  { name: "America/Cancun", value: TimeZone.AMERICA_CANCUN },
  { name: "America/Caracas", value: TimeZone.AMERICA_CARACAS },
  { name: "America/Cayenne", value: TimeZone.AMERICA_CAYENNE },
  { name: "America/Cayman", value: TimeZone.AMERICA_CAYMAN },
  { name: "America/Chicago", value: TimeZone.AMERICA_CHICAGO },
  { name: "America/Chihuahua", value: TimeZone.AMERICA_CHIHUAHUA },
  { name: "America/Ciudad_Juarez", value: TimeZone.AMERICA_CIUDAD_JUAREZ },
  { name: "America/Costa_Rica", value: TimeZone.AMERICA_COSTA_RICA },
  { name: "America/Creston", value: TimeZone.AMERICA_CRESTON },
  { name: "America/Cuiaba", value: TimeZone.AMERICA_CUIABA },
  { name: "America/Curacao", value: TimeZone.AMERICA_CURACAO },
  { name: "America/Danmarkshavn", value: TimeZone.AMERICA_DANMARKSHAVN },
  { name: "America/Dawson", value: TimeZone.AMERICA_DAWSON },
  { name: "America/Dawson_Creek", value: TimeZone.AMERICA_DAWSON_CREEK },
  { name: "America/Denver", value: TimeZone.AMERICA_DENVER },
  { name: "America/Detroit", value: TimeZone.AMERICA_DETROIT },
  { name: "America/Dominica", value: TimeZone.AMERICA_DOMINICA },
  { name: "America/Edmonton", value: TimeZone.AMERICA_EDMONTON },
  { name: "America/Eirunepe", value: TimeZone.AMERICA_EIRUNEPE },
  { name: "America/El_Salvador", value: TimeZone.AMERICA_EL_SALVADOR },
  { name: "America/Fort_Nelson", value: TimeZone.AMERICA_FORT_NELSON },
  { name: "America/Fortaleza", value: TimeZone.AMERICA_FORTALEZA },
  { name: "America/Glace_Bay", value: TimeZone.AMERICA_GLACE_BAY },
  { name: "America/Goose_Bay", value: TimeZone.AMERICA_GOOSE_BAY },
  { name: "America/Grand_Turk", value: TimeZone.AMERICA_GRAND_TURK },
  { name: "America/Grenada", value: TimeZone.AMERICA_GRENADA },
  { name: "America/Guadeloupe", value: TimeZone.AMERICA_GUADELOUPE },
  { name: "America/Guatemala", value: TimeZone.AMERICA_GUATEMALA },
  { name: "America/Guayaquil", value: TimeZone.AMERICA_GUAYAQUIL },
  { name: "America/Guyana", value: TimeZone.AMERICA_GUYANA },
  { name: "America/Halifax", value: TimeZone.AMERICA_HALIFAX },
  { name: "America/Havana", value: TimeZone.AMERICA_HAVANA },
  { name: "America/Hermosillo", value: TimeZone.AMERICA_HERMOSILLO },
  {
    name: "America/Indiana/Indianapolis",
    value: TimeZone.AMERICA_INDIANA_INDIANAPOLIS,
  },
  { name: "America/Indiana/Knox", value: TimeZone.AMERICA_INDIANA_KNOX },
  { name: "America/Indiana/Marengo", value: TimeZone.AMERICA_INDIANA_MARENGO },
  {
    name: "America/Indiana/Petersburg",
    value: TimeZone.AMERICA_INDIANA_PETERSBURG,
  },
  {
    name: "America/Indiana/Tell_City",
    value: TimeZone.AMERICA_INDIANA_TELL_CITY,
  },
  { name: "America/Indiana/Vevay", value: TimeZone.AMERICA_INDIANA_VEVAY },
  {
    name: "America/Indiana/Vincennes",
    value: TimeZone.AMERICA_INDIANA_VINCENNES,
  },
  { name: "America/Indiana/Winamac", value: TimeZone.AMERICA_INDIANA_WINAMAC },
  { name: "America/Inuvik", value: TimeZone.AMERICA_INUVIK },
  { name: "America/Iqaluit", value: TimeZone.AMERICA_IQALUIT },
  { name: "America/Jamaica", value: TimeZone.AMERICA_JAMAICA },
  { name: "America/Juneau", value: TimeZone.AMERICA_JUNEAU },
  {
    name: "America/Kentucky/Louisville",
    value: TimeZone.AMERICA_KENTUCKY_LOUISVILLE,
  },
  {
    name: "America/Kentucky/Monticello",
    value: TimeZone.AMERICA_KENTUCKY_MONTICELLO,
  },
  { name: "America/Kralendijk", value: TimeZone.AMERICA_KRALENDIJK },
  { name: "America/La_Paz", value: TimeZone.AMERICA_LA_PAZ },
  { name: "America/Lima", value: TimeZone.AMERICA_LIMA },
  { name: "America/Los_Angeles", value: TimeZone.AMERICA_LOS_ANGELES },
  { name: "America/Lower_Princes", value: TimeZone.AMERICA_LOWER_PRINCES },
  { name: "America/Maceio", value: TimeZone.AMERICA_MACEIO },
  { name: "America/Managua", value: TimeZone.AMERICA_MANAGUA },
  { name: "America/Manaus", value: TimeZone.AMERICA_MANAUS },
  { name: "America/Marigot", value: TimeZone.AMERICA_MARIGOT },
  { name: "America/Martinique", value: TimeZone.AMERICA_MARTINIQUE },
  { name: "America/Matamoros", value: TimeZone.AMERICA_MATAMOROS },
  { name: "America/Mazatlan", value: TimeZone.AMERICA_MAZATLAN },
  { name: "America/Menominee", value: TimeZone.AMERICA_MENOMINEE },
  { name: "America/Merida", value: TimeZone.AMERICA_MERIDA },
  { name: "America/Metlakatla", value: TimeZone.AMERICA_METLAKATLA },
  { name: "America/Mexico_City", value: TimeZone.AMERICA_MEXICO_CITY },
  { name: "America/Miquelon", value: TimeZone.AMERICA_MIQUELON },
  { name: "America/Moncton", value: TimeZone.AMERICA_MONCTON },
  { name: "America/Monterrey", value: TimeZone.AMERICA_MONTERREY },
  { name: "America/Montevideo", value: TimeZone.AMERICA_MONTEVIDEO },
  { name: "America/Montserrat", value: TimeZone.AMERICA_MONTSERRAT },
  { name: "America/Nassau", value: TimeZone.AMERICA_NASSAU },
  { name: "America/New_York", value: TimeZone.AMERICA_NEW_YORK },
  { name: "America/Nome", value: TimeZone.AMERICA_NOME },
  { name: "America/Noronha", value: TimeZone.AMERICA_NORONHA },
  {
    name: "America/North_Dakota/Beulah",
    value: TimeZone.AMERICA_NORTH_DAKOTA_BEULAH,
  },
  {
    name: "America/North_Dakota/Center",
    value: TimeZone.AMERICA_NORTH_DAKOTA_CENTER,
  },
  {
    name: "America/North_Dakota/New_Salem",
    value: TimeZone.AMERICA_NORTH_DAKOTA_NEW_SALEM,
  },
  { name: "America/Nuku_alofa", value: TimeZone.AMERICA_NUKU_ALOFA },
  { name: "America/Ojinaga", value: TimeZone.AMERICA_OJINAGA },
  { name: "America/Panama", value: TimeZone.AMERICA_PANAMA },
  { name: "America/Paramaribo", value: TimeZone.AMERICA_PARAMARIBO },
  { name: "America/Phoenix", value: TimeZone.AMERICA_PHOENIX },
  { name: "America/Port-au-Prince", value: TimeZone.AMERICA_PORT_AU_PRINCE },
  { name: "America/Port_of_Spain", value: TimeZone.AMERICA_PORT_OF_SPAIN },
  { name: "America/Porto_Velho", value: TimeZone.AMERICA_PORTO_VELHO },
  { name: "America/Puerto_Rico", value: TimeZone.AMERICA_PUERTO_RICO },
  { name: "America/Punta_Arenas", value: TimeZone.AMERICA_PUNTA_ARENAS },
  { name: "America/Rankin_Inlet", value: TimeZone.AMERICA_RANKIN_INLET },
  { name: "America/Recife", value: TimeZone.AMERICA_RECIFE },
  { name: "America/Regina", value: TimeZone.AMERICA_REGINA },
  { name: "America/Resolute", value: TimeZone.AMERICA_RESOLUTE },
  { name: "America/Rio_Branco", value: TimeZone.AMERICA_RIO_BRANCO },
  { name: "America/Santarem", value: TimeZone.AMERICA_SANTAREM },
  { name: "America/Santiago", value: TimeZone.AMERICA_SANTIAGO },
  { name: "America/Santo_Domingo", value: TimeZone.AMERICA_SANTO_DOMINGO },
  { name: "America/Sao_Paulo", value: TimeZone.AMERICA_SAO_PAULO },
  { name: "America/Scoresbysund", value: TimeZone.AMERICA_SCORESBYSUND },
  { name: "America/Sitka", value: TimeZone.AMERICA_SITKA },
  { name: "America/St_Barthelemy", value: TimeZone.AMERICA_ST_BARTHELEMY },
  { name: "America/St_Johns", value: TimeZone.AMERICA_ST_JOHNS },
  { name: "America/St_Kitts", value: TimeZone.AMERICA_ST_KITTS },
  { name: "America/St_Lucia", value: TimeZone.AMERICA_ST_LUCIA },
  { name: "America/St_Thomas", value: TimeZone.AMERICA_ST_THOMAS },
  { name: "America/St_Vincent", value: TimeZone.AMERICA_ST_VINCENT },
  { name: "America/Swift_Current", value: TimeZone.AMERICA_SWIFT_CURRENT },
  { name: "America/Tegucigalpa", value: TimeZone.AMERICA_TEGUCIGALPA },
  { name: "America/Thule", value: TimeZone.AMERICA_THULE },
  { name: "America/Tijuana", value: TimeZone.AMERICA_TIJUANA },
  { name: "America/Toronto", value: TimeZone.AMERICA_TORONTO },
  { name: "America/Tortola", value: TimeZone.AMERICA_TORTOLA },
  { name: "America/Vancouver", value: TimeZone.AMERICA_VANCOUVER },
  { name: "America/Whitehorse", value: TimeZone.AMERICA_WHITEHORSE },
  { name: "America/Winnipeg", value: TimeZone.AMERICA_WINNIPEG },
  { name: "America/Yakutat", value: TimeZone.AMERICA_YAKUTAT },
  { name: "America/Yellowknife", value: TimeZone.AMERICA_YELLOWKNIFE },

  // Antarctica
  { name: "Antarctica/Casey", value: TimeZone.ANTARCTICA_CASEY },
  { name: "Antarctica/Davis", value: TimeZone.ANTARCTICA_DAVIS },
  {
    name: "Antarctica/DumontDUrville",
    value: TimeZone.ANTARCTICA_DUMONTDURVILLE,
  },
  { name: "Antarctica/Macquarie", value: TimeZone.ANTARCTICA_MACQUARIE },
  { name: "Antarctica/Mawson", value: TimeZone.ANTARCTICA_MAWSON },
  { name: "Antarctica/McMurdo", value: TimeZone.ANTARCTICA_MCMURDO },
  { name: "Antarctica/Palmer", value: TimeZone.ANTARCTICA_PALMER },
  { name: "Antarctica/Rothera", value: TimeZone.ANTARCTICA_ROTHERA },
  { name: "Antarctica/Syowa", value: TimeZone.ANTARCTICA_SYOWA },
  { name: "Antarctica/Troll", value: TimeZone.ANTARCTICA_TROLL },
  { name: "Antarctica/Vostok", value: TimeZone.ANTARCTICA_VOSTOK },

  // Arctic
  { name: "Arctic/Longyearbyen", value: TimeZone.ARCTIC_LONGYEARBYEN },

  // Asia
  { name: "Asia/Aden", value: TimeZone.ASIA_ADEN },
  { name: "Asia/Almaty", value: TimeZone.ASIA_ALMATY },
  { name: "Asia/Amman", value: TimeZone.ASIA_AMMAN },
  { name: "Asia/Anadyr", value: TimeZone.ASIA_ANADYR },
  { name: "Asia/Aqtau", value: TimeZone.ASIA_AQTAU },
  { name: "Asia/Aqtobe", value: TimeZone.ASIA_AQTOBE },
  { name: "Asia/Ashgabat", value: TimeZone.ASIA_ASHGABAT },
  { name: "Asia/Atyrau", value: TimeZone.ASIA_ATYRAU },
  { name: "Asia/Baghdad", value: TimeZone.ASIA_BAGHDAD },
  { name: "Asia/Bahrain", value: TimeZone.ASIA_BAHRAIN },
  { name: "Asia/Baku", value: TimeZone.ASIA_BAKU },
  { name: "Asia/Bangkok", value: TimeZone.ASIA_BANGKOK },
  { name: "Asia/Barnaul", value: TimeZone.ASIA_BARNAUL },
  { name: "Asia/Beirut", value: TimeZone.ASIA_BEIRUT },
  { name: "Asia/Bishkek", value: TimeZone.ASIA_BISHKEK },
  { name: "Asia/Brunei", value: TimeZone.ASIA_BRUNEI },
  { name: "Asia/Chita", value: TimeZone.ASIA_CHITA },
  { name: "Asia/Choibalsan", value: TimeZone.ASIA_CHOIBALSAN },
  { name: "Asia/Colombo", value: TimeZone.ASIA_COLOMBO },
  { name: "Asia/Damascus", value: TimeZone.ASIA_DAMASCUS },
  { name: "Asia/Dhaka", value: TimeZone.ASIA_DHAKA },
  { name: "Asia/Dili", value: TimeZone.ASIA_DILI },
  { name: "Asia/Dubai", value: TimeZone.ASIA_DUBAI },
  { name: "Asia/Dushanbe", value: TimeZone.ASIA_DUSHANBE },
  { name: "Asia/Famagusta", value: TimeZone.ASIA_FAMAGUSTA },
  { name: "Asia/Gaza", value: TimeZone.ASIA_GAZA },
  { name: "Asia/Hebron", value: TimeZone.ASIA_HEBRON },
  { name: "Asia/Ho_Chi_Minh", value: TimeZone.ASIA_HO_CHI_MINH },
  { name: "Asia/Hong_Kong", value: TimeZone.ASIA_HONG_KONG },
  { name: "Asia/Hovd", value: TimeZone.ASIA_HOVD },
  { name: "Asia/Irkutsk", value: TimeZone.ASIA_IRKUTSK },
  { name: "Asia/Jakarta", value: TimeZone.ASIA_JAKARTA },
  { name: "Asia/Jayapura", value: TimeZone.ASIA_JAYAPURA },
  { name: "Asia/Jerusalem", value: TimeZone.ASIA_JERUSALEM },
  { name: "Asia/Kabul", value: TimeZone.ASIA_KABUL },
  { name: "Asia/Kamchatka", value: TimeZone.ASIA_KAMCHATKA },
  { name: "Asia/Karachi", value: TimeZone.ASIA_KARACHI },
  { name: "Asia/Kathmandu", value: TimeZone.ASIA_KATHMANDU },
  { name: "Asia/Khandyga", value: TimeZone.ASIA_KHANDYGA },
  { name: "Asia/Kolkata", value: TimeZone.ASIA_KOLKATA },
  { name: "Asia/Krasnoyarsk", value: TimeZone.ASIA_KRASNOYARSK },
  { name: "Asia/Kuala_Lumpur", value: TimeZone.ASIA_KUALA_LUMPUR },
  { name: "Asia/Kuching", value: TimeZone.ASIA_KUCHING },
  { name: "Asia/Kuwait", value: TimeZone.ASIA_KUWAIT },
  { name: "Asia/Macau", value: TimeZone.ASIA_MACAU },
  { name: "Asia/Magadan", value: TimeZone.ASIA_MAGADAN },
  { name: "Asia/Makassar", value: TimeZone.ASIA_MAKASSAR },
  { name: "Asia/Manila", value: TimeZone.ASIA_MANILA },
  { name: "Asia/Muscat", value: TimeZone.ASIA_MUSCAT },
  { name: "Asia/Nicosia", value: TimeZone.ASIA_NICOSIA },
  { name: "Asia/Novokuznetsk", value: TimeZone.ASIA_NOVOKUZNETSK },
  { name: "Asia/Novosibirsk", value: TimeZone.ASIA_NOVOSIBIRSK },
  { name: "Asia/Omsk", value: TimeZone.ASIA_OMSK },
  { name: "Asia/Oral", value: TimeZone.ASIA_ORAL },
  { name: "Asia/Phnom_Penh", value: TimeZone.ASIA_PHNOM_PENH },
  { name: "Asia/Pontianak", value: TimeZone.ASIA_PONTIANAK },
  { name: "Asia/Pyongyang", value: TimeZone.ASIA_PYONGYANG },
  { name: "Asia/Qatar", value: TimeZone.ASIA_QATAR },
  { name: "Asia/Qostanay", value: TimeZone.ASIA_QOSTANAY },
  { name: "Asia/Qyzylorda", value: TimeZone.ASIA_QYZYLORDA },
  { name: "Asia/Riyadh", value: TimeZone.ASIA_RIYADH },
  { name: "Asia/Sakhalin", value: TimeZone.ASIA_SAKHALIN },
  { name: "Asia/Samarkand", value: TimeZone.ASIA_SAMARKAND },
  { name: "Asia/Seoul", value: TimeZone.ASIA_SEOUL },
  { name: "Asia/Shanghai", value: TimeZone.ASIA_SHANGHAI },
  { name: "Asia/Singapore", value: TimeZone.ASIA_SINGAPORE },
  { name: "Asia/Srednekolymsk", value: TimeZone.ASIA_SREDNEKOLYMSK },
  { name: "Asia/Taipei", value: TimeZone.ASIA_TAIPEI },
  { name: "Asia/Tashkent", value: TimeZone.ASIA_TASHKENT },
  { name: "Asia/Tbilisi", value: TimeZone.ASIA_TBILISI },
  { name: "Asia/Tehran", value: TimeZone.ASIA_TEHRAN },
  { name: "Asia/Thimphu", value: TimeZone.ASIA_THIMPHU },
  { name: "Asia/Tokyo", value: TimeZone.ASIA_TOKYO },
  { name: "Asia/Tomsk", value: TimeZone.ASIA_TOMSK },
  { name: "Asia/Ulaanbaatar", value: TimeZone.ASIA_ULAANBAATAR },
  { name: "Asia/Urumqi", value: TimeZone.ASIA_URUMQI },
  { name: "Asia/Ust-Nera", value: TimeZone.ASIA_UST_NERA },
  { name: "Asia/Vientiane", value: TimeZone.ASIA_VIENTIANE },
  { name: "Asia/Vladivostok", value: TimeZone.ASIA_VLADIVOSTOK },
  { name: "Asia/Yakutsk", value: TimeZone.ASIA_YAKUTSK },
  { name: "Asia/Yangon", value: TimeZone.ASIA_YANGON },
  { name: "Asia/Yekaterinburg", value: TimeZone.ASIA_YEKATERINBURG },
  { name: "Asia/Yerevan", value: TimeZone.ASIA_YEREVAN },

  // Atlantic
  { name: "Atlantic/Azores", value: TimeZone.ATLANTIC_AZORES },
  { name: "Atlantic/Bermuda", value: TimeZone.ATLANTIC_BERMUDA },
  { name: "Atlantic/Canary", value: TimeZone.ATLANTIC_CANARY },
  { name: "Atlantic/Cape_Verde", value: TimeZone.ATLANTIC_CAPE_VERDE },
  { name: "Atlantic/Faroe", value: TimeZone.ATLANTIC_FAROE },
  { name: "Atlantic/Madeira", value: TimeZone.ATLANTIC_MADEIRA },
  { name: "Atlantic/Reykjavik", value: TimeZone.ATLANTIC_REYKJAVIK },
  { name: "Atlantic/South_Georgia", value: TimeZone.ATLANTIC_SOUTH_GEORGIA },
  { name: "Atlantic/St_Helena", value: TimeZone.ATLANTIC_ST_HELENA },
  { name: "Atlantic/Stanley", value: TimeZone.ATLANTIC_STANLEY },

  // Australia
  { name: "Australia/Adelaide", value: TimeZone.AUSTRALIA_ADELAIDE },
  { name: "Australia/Brisbane", value: TimeZone.AUSTRALIA_BRISBANE },
  { name: "Australia/Broken_Hill", value: TimeZone.AUSTRALIA_BROKEN_HILL },
  { name: "Australia/Darwin", value: TimeZone.AUSTRALIA_DARWIN },
  { name: "Australia/Eucla", value: TimeZone.AUSTRALIA_EUCLA },
  { name: "Australia/Hobart", value: TimeZone.AUSTRALIA_HOBART },
  { name: "Australia/Lindeman", value: TimeZone.AUSTRALIA_LINDEMAN },
  { name: "Australia/Lord_Howe", value: TimeZone.AUSTRALIA_LORD_HOWE },
  { name: "Australia/Melbourne", value: TimeZone.AUSTRALIA_MELBOURNE },
  { name: "Australia/Perth", value: TimeZone.AUSTRALIA_PERTH },
  { name: "Australia/Sydney", value: TimeZone.AUSTRALIA_SYDNEY },

  // Europe
  { name: "Europe/Amsterdam", value: TimeZone.EUROPE_AMSTERDAM },
  { name: "Europe/Andorra", value: TimeZone.EUROPE_ANDORRA },
  { name: "Europe/Astrakhan", value: TimeZone.EUROPE_ASTRAKHAN },
  { name: "Europe/Athens", value: TimeZone.EUROPE_ATHENS },
  { name: "Europe/Belgrade", value: TimeZone.EUROPE_BELGRADE },
  { name: "Europe/Berlin", value: TimeZone.EUROPE_BERLIN },
  { name: "Europe/Bratislava", value: TimeZone.EUROPE_BRATISLAVA },
  { name: "Europe/Brussels", value: TimeZone.EUROPE_BRUSSELS },
  { name: "Europe/Bucharest", value: TimeZone.EUROPE_BUCHAREST },
  { name: "Europe/Budapest", value: TimeZone.EUROPE_BUDAPEST },
  { name: "Europe/Busingen", value: TimeZone.EUROPE_BUSINGEN },
  { name: "Europe/Chisinau", value: TimeZone.EUROPE_CHISINAU },
  { name: "Europe/Copenhagen", value: TimeZone.EUROPE_COPENHAGEN },
  { name: "Europe/Dublin", value: TimeZone.EUROPE_DUBLIN },
  { name: "Europe/Gibraltar", value: TimeZone.EUROPE_GIBRALTAR },
  { name: "Europe/Guernsey", value: TimeZone.EUROPE_GUERNSEY },
  { name: "Europe/Helsinki", value: TimeZone.EUROPE_HELSINKI },
  { name: "Europe/Isle_of_Man", value: TimeZone.EUROPE_ISLE_OF_MAN },
  { name: "Europe/Istanbul", value: TimeZone.EUROPE_ISTANBUL },
  { name: "Europe/Jersey", value: TimeZone.EUROPE_JERSEY },
  { name: "Europe/Kaliningrad", value: TimeZone.EUROPE_KALININGRAD },
  { name: "Europe/Kiev", value: TimeZone.EUROPE_KIEV },
  { name: "Europe/Kirov", value: TimeZone.EUROPE_KIROV },
  { name: "Europe/Lisbon", value: TimeZone.EUROPE_LISBON },
  { name: "Europe/Ljubljana", value: TimeZone.EUROPE_LJUBLJANA },
  { name: "Europe/London", value: TimeZone.EUROPE_LONDON },
  { name: "Europe/Luxembourg", value: TimeZone.EUROPE_LUXEMBOURG },
  { name: "Europe/Madrid", value: TimeZone.EUROPE_MADRID },
  { name: "Europe/Malta", value: TimeZone.EUROPE_MALTA },
  { name: "Europe/Mariehamn", value: TimeZone.EUROPE_MARIEHAMN },
  { name: "Europe/Minsk", value: TimeZone.EUROPE_MINSK },
  { name: "Europe/Monaco", value: TimeZone.EUROPE_MONACO },
  { name: "Europe/Moscow", value: TimeZone.EUROPE_MOSCOW },
  { name: "Europe/Oslo", value: TimeZone.EUROPE_OSLO },
  { name: "Europe/Paris", value: TimeZone.EUROPE_PARIS },
  { name: "Europe/Podgorica", value: TimeZone.EUROPE_PODGORICA },
  { name: "Europe/Prague", value: TimeZone.EUROPE_PRAGUE },
  { name: "Europe/Riga", value: TimeZone.EUROPE_RIGA },
  { name: "Europe/Rome", value: TimeZone.EUROPE_ROME },
  { name: "Europe/Samara", value: TimeZone.EUROPE_SAMARA },
  { name: "Europe/San_Marino", value: TimeZone.EUROPE_SAN_MARINO },
  { name: "Europe/Sarajevo", value: TimeZone.EUROPE_SARAJEVO },
  { name: "Europe/Saratov", value: TimeZone.EUROPE_SARATOV },
  { name: "Europe/Simferopol", value: TimeZone.EUROPE_SIMFEROPOL },
  { name: "Europe/Skopje", value: TimeZone.EUROPE_SKOPJE },
  { name: "Europe/Sofia", value: TimeZone.EUROPE_SOFIA },
  { name: "Europe/Stockholm", value: TimeZone.EUROPE_STOCKHOLM },
  { name: "Europe/Tallinn", value: TimeZone.EUROPE_TALLINN },
  { name: "Europe/Tirane", value: TimeZone.EUROPE_TIRANE },
  { name: "Europe/Ulyanovsk", value: TimeZone.EUROPE_ULYANOVSK },
  { name: "Europe/Uzhgorod", value: TimeZone.EUROPE_UZHGOROD },
  { name: "Europe/Vaduz", value: TimeZone.EUROPE_VADUZ },
  { name: "Europe/Vatican", value: TimeZone.EUROPE_VATICAN },
  { name: "Europe/Vienna", value: TimeZone.EUROPE_VIENNA },
  { name: "Europe/Vilnius", value: TimeZone.EUROPE_VILNIUS },
  { name: "Europe/Volgograd", value: TimeZone.EUROPE_VOLGOGRAD },
  { name: "Europe/Warsaw", value: TimeZone.EUROPE_WARSAW },
  { name: "Europe/Zagreb", value: TimeZone.EUROPE_ZAGREB },
  { name: "Europe/Zaporozhye", value: TimeZone.EUROPE_ZAPOROZHYE },
  { name: "Europe/Zurich", value: TimeZone.EUROPE_ZURICH },

  // Indian
  { name: "Indian/Antananarivo", value: TimeZone.INDIAN_ANTANANARIVO },
  { name: "Indian/Chagos", value: TimeZone.INDIAN_CHAGOS },
  { name: "Indian/Christmas", value: TimeZone.INDIAN_CHRISTMAS },
  { name: "Indian/Cocos", value: TimeZone.INDIAN_COCOS },
  { name: "Indian/Comoro", value: TimeZone.INDIAN_COMORO },
  { name: "Indian/Kerguelen", value: TimeZone.INDIAN_KERGUELEN },
  { name: "Indian/Mahe", value: TimeZone.INDIAN_MAHE },
  { name: "Indian/Maldives", value: TimeZone.INDIAN_MALDIVES },
  { name: "Indian/Mauritius", value: TimeZone.INDIAN_MAURITIUS },
  { name: "Indian/Mayotte", value: TimeZone.INDIAN_MAYOTTE },
  { name: "Indian/Reunion", value: TimeZone.INDIAN_REUNION },

  // Pacific
  { name: "Pacific/Apia", value: TimeZone.PACIFIC_APIA },
  { name: "Pacific/Auckland", value: TimeZone.PACIFIC_AUCKLAND },
  { name: "Pacific/Bougainville", value: TimeZone.PACIFIC_BOUGAINVILLE },
  { name: "Pacific/Chatham", value: TimeZone.PACIFIC_CHATHAM },
  { name: "Pacific/Chuuk", value: TimeZone.PACIFIC_CHUUK },
  { name: "Pacific/Easter", value: TimeZone.PACIFIC_EASTER },
  { name: "Pacific/Efate", value: TimeZone.PACIFIC_EFATE },
  { name: "Pacific/Fakaofo", value: TimeZone.PACIFIC_FAKAOFO },
  { name: "Pacific/Fiji", value: TimeZone.PACIFIC_FIJI },
  { name: "Pacific/Funafuti", value: TimeZone.PACIFIC_FUNAFUTI },
  { name: "Pacific/Galapagos", value: TimeZone.PACIFIC_GALAPAGOS },
  { name: "Pacific/Gambier", value: TimeZone.PACIFIC_GAMBIER },
  { name: "Pacific/Guadalcanal", value: TimeZone.PACIFIC_GUADALCANAL },
  { name: "Pacific/Guam", value: TimeZone.PACIFIC_GUAM },
  { name: "Pacific/Honolulu", value: TimeZone.PACIFIC_HONOLULU },
  { name: "Pacific/Kiritimati", value: TimeZone.PACIFIC_KIRITIMATI },
  { name: "Pacific/Kosrae", value: TimeZone.PACIFIC_KOSRAE },
  { name: "Pacific/Kwajalein", value: TimeZone.PACIFIC_KWAJALEIN },
  { name: "Pacific/Majuro", value: TimeZone.PACIFIC_MAJURO },
  { name: "Pacific/Marquesas", value: TimeZone.PACIFIC_MARQUESAS },
  { name: "Pacific/Midway", value: TimeZone.PACIFIC_MIDWAY },
  { name: "Pacific/Nauru", value: TimeZone.PACIFIC_NAURU },
  { name: "Pacific/Niue", value: TimeZone.PACIFIC_NIUE },
  { name: "Pacific/Norfolk", value: TimeZone.PACIFIC_NORFOLK },
  { name: "Pacific/Noumea", value: TimeZone.PACIFIC_NOUMEA },
  { name: "Pacific/Pago_Pago", value: TimeZone.PACIFIC_PAGO_PAGO },
  { name: "Pacific/Palau", value: TimeZone.PACIFIC_PALAU },
  { name: "Pacific/Pitcairn", value: TimeZone.PACIFIC_PITCAIRN },
  { name: "Pacific/Pohnpei", value: TimeZone.PACIFIC_POHNPEI },
  { name: "Pacific/Port_Moresby", value: TimeZone.PACIFIC_PORT_MORESBY },
  { name: "Pacific/Rarotonga", value: TimeZone.PACIFIC_RAROTONGA },
  { name: "Pacific/Saipan", value: TimeZone.PACIFIC_SAIPAN },
  { name: "Pacific/Tahiti", value: TimeZone.PACIFIC_TAHITI },
  { name: "Pacific/Tarawa", value: TimeZone.PACIFIC_TARAWA },
  { name: "Pacific/Tongatapu", value: TimeZone.PACIFIC_TONGATAPU },
  { name: "Pacific/Wake", value: TimeZone.PACIFIC_WAKE },
  { name: "Pacific/Wallis", value: TimeZone.PACIFIC_WALLIS },

  // UTC/GMT
  //   { name: "Etc/GMT", value: TimeZone.ETC_GMT },
  //   { name: "Etc/GMT+0", value: TimeZone.ETC_GMT_PLUS_0 },
  //   { name: "Etc/GMT+1", value: TimeZone.ETC_GMT_PLUS_1 },
  //   { name: "Etc/GMT+10", value: TimeZone.ETC_GMT_PLUS_10 },
  //   { name: "Etc/GMT+11", value: TimeZone.ETC_GMT_PLUS_11 },
  //   { name: "Etc/GMT+12", value: TimeZone.ETC_GMT_PLUS_12 },
  //   { name: "Etc/GMT+2", value: TimeZone.ETC_GMT_PLUS_2 },
  //   { name: "Etc/GMT+3", value: TimeZone.ETC_GMT_PLUS_3 },
  //   { name: "Etc/GMT+4", value: TimeZone.ETC_GMT_PLUS_4 },
  //   { name: "Etc/GMT+5", value: TimeZone.ETC_GMT_PLUS_5 },
  //   { name: "Etc/GMT+6", value: TimeZone.ETC_GMT_PLUS_6 },
  //   { name: "Etc/GMT+7", value: TimeZone.ETC_GMT_PLUS_7 },
  //   { name: "Etc/GMT+8", value: TimeZone.ETC_GMT_PLUS_8 },
  //   { name: "Etc/GMT+9", value: TimeZone.ETC_GMT_PLUS_9 },
  //   { name: "Etc/GMT-0", value: TimeZone.ETC_GMT_MINUS_0 },
  //   { name: "Etc/GMT-1", value: TimeZone.ETC_GMT_MINUS_1 },
  //   { name: "Etc/GMT-10", value: TimeZone.ETC_GMT_MINUS_10 },
  //   { name: "Etc/GMT-11", value: TimeZone.ETC_GMT_MINUS_11 },
  //   { name: "Etc/GMT-12", value: TimeZone.ETC_GMT_MINUS_12 },
  //   { name: "Etc/GMT-13", value: TimeZone.ETC_GMT_MINUS_13 },
  //   { name: "Etc/GMT-14", value: TimeZone.ETC_GMT_MINUS_14 },
  //   { name: "Etc/GMT-2", value: TimeZone.ETC_GMT_MINUS_2 },
  //   { name: "Etc/GMT-3", value: TimeZone.ETC_GMT_MINUS_3 },
  //   { name: "Etc/GMT-4", value: TimeZone.ETC_GMT_MINUS_4 },
  //   { name: "Etc/GMT-5", value: TimeZone.ETC_GMT_MINUS_5 },
  //   { name: "Etc/GMT-6", value: TimeZone.ETC_GMT_MINUS_6 },
  //   { name: "Etc/GMT-7", value: TimeZone.ETC_GMT_MINUS_7 },
  //   { name: "Etc/GMT-8", value: TimeZone.ETC_GMT_MINUS_8 },
  //   { name: "Etc/GMT-9", value: TimeZone.ETC_GMT_MINUS_9 },
  //   { name: "Etc/UCT", value: TimeZone.ETC_UCT },
  //   { name: "Etc/UTC", value: TimeZone.ETC_UTC },
];
