import { RestCountry } from "./types";

export const REST_COUNTRIES: RestCountry[] = [
  {
    iso: "AD",
    name: "Andorra",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["AD", "Andorra", "Principality of Andorra"],
  },
  {
    iso: "AE",
    name: "United Arab Emirates",
    currency_code: "AED",
    symbol: "AED",
    dateFormat: "dd/MM/yyyy",
    numericCode: 784,
    aliases: ["AE", "United Arab Emirates", "UAE"],
  },
  {
    iso: "AF",
    name: "Afghanistan",
    currency_code: "AFN",
    symbol: "Af",
    numericCode: 971,
    aliases: [
      "AF",
      "Afghanistan",
      "Islamic Emirate of Afghanistan",
      "Emirate of Afghanistan",
    ],
  },
  {
    iso: "AG",
    name: "Antigua and Barbuda",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["AG", "Antigua and Barbuda", "Antigua", "Barbuda"],
  },
  {
    iso: "AI",
    name: "Anguilla",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["AI", "Anguilla"],
  },
  {
    iso: "AL",
    name: "Albania",
    currency_code: "ALL",
    symbol: "ALL",
    dateFormat: "yyyy-MM-dd",
    numericCode: 8,
    aliases: ["AL", "Albania", "Republic of Albania"],
  },
  {
    iso: "AM",
    name: "Armenia",
    currency_code: "AMD",
    symbol: "AMD",
    numericCode: 51,
    aliases: ["AM", "Armenia", "Republic of Armenia"],
  },
  {
    iso: "AO",
    name: "Angola",
    currency_code: "AOA",
    symbol: "AOA",
    numericCode: 973,
    aliases: ["AO", "Angola", "Republic of Angola"],
  },
  {
    iso: "AR",
    name: "Argentina",
    currency_code: "ARS",
    symbol: "AR$",
    dateFormat: "dd/MM/yyyy",
    numericCode: 32,
    aliases: ["AR", "Argentina", "Argentine Republic"],
  },
  {
    iso: "AS",
    name: "American Samoa",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["AS", "American Samoa"],
  },
  {
    iso: "AT",
    name: "Austria",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd.MM.yyyy",
    numericCode: 978,
    aliases: ["AT", "Austria", "Republic of Austria"],
  },
  {
    iso: "AU",
    name: "Australia",
    currency_code: "AUD",
    symbol: "$",
    dateFormat: "d/MM/yyyy",
    numericCode: 36,
    aliases: ["AU", "Australia", "Commonwealth of Australia"],
  },
  {
    iso: "AW",
    name: "Aruba",
    currency_code: "AWG",
    symbol: "AWG",
    numericCode: 533,
    aliases: ["AW", "Aruba", "Country of Aruba"],
  },
  {
    iso: "AX",
    name: "Aland Islands",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["AX", "Aland Islands", "Aland", "Åland"],
  },
  {
    iso: "AZ",
    name: "Azerbaijan",
    currency_code: "AZN",
    symbol: "man.",
    numericCode: 944,
    aliases: ["AZ", "Azerbaijan", "Republic of Azerbaijan"],
  },
  {
    iso: "BA",
    name: "Bosnia and Herzegovina",
    currency_code: "BAM",
    symbol: "KM",
    dateFormat: "yyyy-MM-dd",
    numericCode: 977,
    aliases: [
      "BA",
      "Bosnia and Herzegovina",
      "Bosnia",
      "Herzegovina",
      "Bosnia-Herzegovina",
    ],
  },
  {
    iso: "BB",
    name: "Barbados",
    currency_code: "BBD",
    symbol: "BBD",
    numericCode: 52,
    aliases: ["BB", "Barbados"],
  },
  {
    iso: "BD",
    name: "Bangladesh",
    currency_code: "BDT",
    symbol: "Tk",
    numericCode: 50,
    aliases: ["BD", "Bangladesh", "People's Republic of Bangladesh"],
  },
  {
    iso: "BE",
    name: "Belgium",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d/MM/yyyy",
    numericCode: 978,
    aliases: ["BE", "Belgium", "Kingdom of Belgium"],
  },
  {
    iso: "BF",
    name: "Burkina Faso",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: ["BF", "Burkina Faso"],
  },
  {
    iso: "BG",
    name: "Bulgaria",
    currency_code: "BGN",
    symbol: "BGN",
    dateFormat: "yyyy-M-d",
    numericCode: 975,
    aliases: ["BG", "Bulgaria", "Republic of Bulgaria"],
  },
  {
    iso: "BH",
    name: "Bahrain",
    currency_code: "BHD",
    symbol: "BD",
    dateFormat: "dd/MM/yyyy",
    numericCode: 48,
    aliases: ["BH", "Bahrain", "Kingdom of Bahrain"],
  },
  {
    iso: "BI",
    name: "Burundi",
    currency_code: "BIF",
    symbol: "FBu",
    numericCode: 108,
    aliases: ["BI", "Burundi", "Republic of Burundi"],
  },
  {
    iso: "BJ",
    name: "Benin",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: ["BJ", "Benin", "Republic of Benin", "Dahomey"],
  },
  {
    iso: "BL",
    name: "Saint Barthelemy",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: [
      "BL",
      "Saint Barthelemy",
      "St. Barthelemy",
      "Collectivité territoriale de Saint-Barthélemy",
      "St. Barts",
      "St. Barth",
      "Saint Barthélemy",
    ],
  },
  {
    iso: "BM",
    name: "Bermuda",
    currency_code: "BMD",
    symbol: "BMD",
    numericCode: 60,
    aliases: ["BM", "Bermuda", "the Bermudas", "Somers Isles"],
  },
  {
    iso: "BN",
    name: "Brunei",
    currency_code: "BND",
    symbol: "BN$",
    numericCode: 96,
    aliases: ["BN", "Brunei", "Brunei Darussalam"],
  },
  {
    iso: "BO",
    name: "Bolivia",
    currency_code: "BOB",
    symbol: "Bs",
    dateFormat: "dd-MM-yyyy",
    numericCode: 68,
    aliases: ["BO", "Bolivia", "Plurinational State of Bolivia"],
  },
  {
    iso: "BQ",
    name: "Bonaire, Saint Eustatius and Saba ",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: [
      "BQ",
      "Bonaire, Saint Eustatius and Saba ",
      "Bonaire",
      "Saint Eustatius",
      "Saba",
    ],
  },
  {
    iso: "BR",
    name: "Brazil",
    currency_code: "BRL",
    symbol: "R$",
    dateFormat: "dd/MM/yyyy",
    numericCode: 986,
    aliases: [
      "BR",
      "Brazil",
      "Federative Republic of Brazil",
      "Brazilian Republic",
      "Brasil",
    ],
  },
  {
    iso: "BS",
    name: "Bahamas",
    currency_code: "BSD",
    symbol: "BSD",
    numericCode: 44,
    aliases: ["BS", "Bahamas", "Commonwealth of The Bahamas"],
  },
  {
    iso: "BT",
    name: "Bhutan",
    currency_code: "BTN",
    symbol: "BTN",
    numericCode: 64,
    aliases: ["BT", "Bhutan", "Kingdom of Bhutan"],
  },
  {
    iso: "BV",
    name: "Bouvet Island",
    currency_code: "NOK",
    symbol: "Nkr",
    numericCode: 578,
    aliases: ["BV", "Bouvet Island"],
  },
  {
    iso: "BW",
    name: "Botswana",
    currency_code: "BWP",
    symbol: "BWP",
    numericCode: 72,
    aliases: ["BW", "Botswana", "Republic of Botswana"],
  },
  {
    iso: "BY",
    name: "Belarus",
    currency_code: "BYN",
    symbol: "BYN",
    dateFormat: "d.M.yyyy",
    numericCode: 933,
    aliases: ["BY", "Belarus", "Republic of Belarus"],
  },
  {
    iso: "BZ",
    name: "Belize",
    currency_code: "BZD",
    symbol: "BZ$",
    numericCode: 84,
    aliases: ["BZ", "Belize"],
  },
  {
    iso: "CA",
    name: "Canada",
    currency_code: "CAD",
    symbol: "CA$",
    dateFormat: "dd/MM/yyyy",
    numericCode: 124,
    aliases: ["CA", "Canada"],
  },
  {
    iso: "CC",
    name: "Cocos Islands",
    currency_code: "AUD",
    symbol: "AU$",
    numericCode: 36,
    aliases: ["CC", "Cocos Islands", "Keeling Islands"],
  },
  {
    iso: "CD",
    name: "Democratic Republic of the Congo",
    currency_code: "CDF",
    symbol: "CDF",
    numericCode: 976,
    aliases: [
      "CD",
      "Democratic Republic of the Congo",
      "Congo-Kinshasa",
      "DR Congo",
      "DRC",
      "Congo",
    ],
  },
  {
    iso: "CF",
    name: "Central African Republic",
    currency_code: "XAF",
    symbol: "FCFA",
    numericCode: 950,
    aliases: ["CF", "Central African Republic", "CAR"],
  },
  {
    iso: "CG",
    name: "Republic of the Congo",
    currency_code: "XAF",
    symbol: "FCFA",
    numericCode: 950,
    aliases: [
      "CG",
      "Republic of the Congo",
      "Congo-Brazzaville",
      "Congo Republic",
      "Congo",
    ],
  },
  {
    iso: "CH",
    name: "Switzerland",
    currency_code: "CHF",
    symbol: "CHF",
    dateFormat: "dd.MM.yyyy",
    numericCode: 756,
    aliases: ["CH", "Switzerland", "Swiss Confederation", "Helvetia"],
  },
  {
    iso: "CI",
    name: "Ivory Coast",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: ["CI", "Ivory Coast", "Côte d'Ivoire"],
  },
  {
    iso: "CK",
    name: "Cook Islands",
    currency_code: "NZD",
    symbol: "NZ$",
    numericCode: 554,
    aliases: ["CK", "Cook Islands"],
  },
  {
    iso: "CL",
    name: "Chile",
    currency_code: "CLP",
    symbol: "CL$",
    dateFormat: "dd-MM-yyyy",
    numericCode: 152,
    aliases: ["CL", "Chile", "Republic of Chile"],
  },
  {
    iso: "CM",
    name: "Cameroon",
    currency_code: "XAF",
    symbol: "FCFA",
    numericCode: 950,
    aliases: ["CM", "Cameroon", "Republic of Cameroon"],
  },
  {
    iso: "CN",
    name: "China",
    currency_code: "CNY",
    symbol: "CN¥",
    dateFormat: "yyyy-M-d",
    numericCode: 156,
    aliases: ["CN", "China", "People's Republic of China", "PRC"],
  },
  {
    iso: "CO",
    name: "Colombia",
    currency_code: "COP",
    symbol: "CO$",
    dateFormat: "d/MM/yyyy",
    numericCode: 170,
    aliases: ["CO", "Colombia", "Republic of Colombia"],
  },
  {
    iso: "CR",
    name: "Costa Rica",
    currency_code: "CRC",
    symbol: "₡",
    dateFormat: "dd/MM/yyyy",
    numericCode: 188,
    aliases: ["CR", "Costa Rica", "Republic of Costa Rica"],
  },
  {
    iso: "CU",
    name: "Cuba",
    currency_code: "CUP",
    symbol: "CUP",
    numericCode: 192,
    aliases: ["CU", "Cuba", "Republic of Cuba"],
  },
  {
    iso: "CV",
    name: "Cape Verde",
    currency_code: "CVE",
    symbol: "CV$",
    numericCode: 132,
    aliases: ["CV", "Cape Verde", "Republic of Cabo Verde", "Cabo Verde"],
  },
  {
    iso: "CW",
    name: "Curacao",
    currency_code: "ANG",
    symbol: "ANG",
    numericCode: 532,
    aliases: ["CW", "Curacao", "Curaçao", "Country of Curaçao"],
  },
  {
    iso: "CX",
    name: "Christmas Island",
    currency_code: "AUD",
    symbol: "AU$",
    numericCode: 36,
    aliases: ["CX", "Christmas Island", "Territory of Christmas Island"],
  },
  {
    iso: "CY",
    name: "Cyprus",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd/MM/yyyy",
    numericCode: 978,
    aliases: ["CY", "Cyprus", "Republic of Cyprus"],
  },
  {
    iso: "CZ",
    name: "Czech Republic",
    currency_code: "CZK",
    symbol: "Kč",
    dateFormat: "d.M.yyyy",
    numericCode: 203,
    aliases: ["CZ", "Czech Republic", "Czechia", "Czechoslovakia"],
  },
  {
    iso: "DE",
    name: "Germany",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd.MM.yyyy",
    numericCode: 978,
    aliases: ["DE", "Germany", "Federal Republic of Germany", "Deutschland"],
  },
  {
    iso: "DJ",
    name: "Djibouti",
    currency_code: "DJF",
    symbol: "Fdj",
    numericCode: 262,
    aliases: ["DJ", "Djibouti", "Republic of Djibouti"],
  },
  {
    iso: "DK",
    name: "Denmark",
    currency_code: "DKK",
    symbol: "Dkr",
    dateFormat: "dd-MM-yyyy",
    numericCode: 208,
    aliases: ["DK", "Denmark", "Kingdom of Denmark", "Danish Realm", "Danmark"],
  },
  {
    iso: "DM",
    name: "Dominica",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["DM", "Dominica", "Commonwealth of Dominica"],
  },
  {
    iso: "DO",
    name: "Dominican Republic",
    currency_code: "DOP",
    symbol: "RD$",
    dateFormat: "MM/dd/yyyy",
    numericCode: 214,
    aliases: ["DO", "Dominican Republic"],
  },
  {
    iso: "DZ",
    name: "Algeria",
    currency_code: "DZD",
    symbol: "DA",
    dateFormat: "dd/MM/yyyy",
    numericCode: 12,
    aliases: ["DZ", "Algeria", "People's Democratic Republic of Algeria"],
  },
  {
    iso: "EC",
    name: "Ecuador",
    currency_code: "USD",
    symbol: "$",
    dateFormat: "dd/MM/yyyy",
    numericCode: 840,
    aliases: ["EC", "Ecuador", "Republic of Ecuador"],
  },
  {
    iso: "EE",
    name: "Estonia",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d.MM.yyyy",
    numericCode: 978,
    aliases: ["EE", "Estonia", "Republic of Estonia"],
  },
  {
    iso: "EG",
    name: "Egypt",
    currency_code: "EGP",
    symbol: "EGP",
    dateFormat: "dd/MM/yyyy",
    numericCode: 818,
    aliases: ["EG", "Egypt", "Arab Republic of Egypt"],
  },
  {
    iso: "EH",
    name: "Western Sahara",
    currency_code: "MAD",
    symbol: "MAD",
    numericCode: 504,
    aliases: ["EH", "Western Sahara", "Sahrawi Arab Democratic Republic"],
  },
  {
    iso: "ER",
    name: "Eritrea",
    currency_code: "ERN",
    symbol: "Nfk",
    numericCode: 232,
    aliases: ["ER", "Eritrea", "State of Eritrea"],
  },
  {
    iso: "ES",
    name: "Spain",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd/MM/yyyy",
    numericCode: 978,
    aliases: ["ES", "Spain", "Kingdom of Spain"],
  },
  {
    iso: "ET",
    name: "Ethiopia",
    currency_code: "ETB",
    symbol: "Br",
    numericCode: 230,
    aliases: ["ET", "Ethiopia", "Federal Democratic Republic of Ethiopia"],
  },
  {
    iso: "FI",
    name: "Finland",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d.M.yyyy",
    numericCode: 978,
    aliases: ["FI", "Finland", "Republic of Finland"],
  },
  {
    iso: "FJ",
    name: "Fiji",
    currency_code: "FJD",
    symbol: "FJD",
    numericCode: 242,
    aliases: ["FJ", "Fiji", "Republic of Fiji"],
  },
  {
    iso: "FK",
    name: "Falkland Islands",
    currency_code: "FKP",
    symbol: "FKP",
    numericCode: 238,
    aliases: ["FK", "Falkland Islands", "Malvinas"],
  },
  {
    iso: "FM",
    name: "Micronesia",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["FM", "Micronesia", "Federated States of Micronesia"],
  },
  {
    iso: "FO",
    name: "Faroe Islands",
    currency_code: "DKK",
    symbol: "Dkr",
    numericCode: 208,
    aliases: ["FO", "Faroe Islands", "Føroyar", "Færøerne"],
  },
  {
    iso: "FR",
    name: "France",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd/MM/yyyy",
    numericCode: 978,
    aliases: ["FR", "France", "French Republic"],
  },
  {
    iso: "GA",
    name: "Gabon",
    currency_code: "XAF",
    symbol: "FCFA",
    numericCode: 950,
    aliases: ["GA", "Gabon", "Gabonese Republic"],
  },
  {
    iso: "GB",
    name: "United Kingdom",
    currency_code: "GBP",
    symbol: "£",
    dateFormat: "dd/MM/yyyy",
    numericCode: 826,
    aliases: [
      "GB",
      "United Kingdom",
      "UK",
      "U.K",
      "Great Britain",
      "United Kingdom of Great Britain and Northern Ireland",
    ],
  },
  {
    iso: "GD",
    name: "Grenada",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["GD", "Grenada"],
  },
  {
    iso: "GE",
    name: "Georgia",
    currency_code: "GEL",
    symbol: "GEL",
    numericCode: 981,
    aliases: ["GE", "Georgia"],
  },
  {
    iso: "GF",
    name: "French Guiana",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["GF", "French Guiana"],
  },
  {
    iso: "GG",
    name: "Guernsey",
    currency_code: "GBP",
    symbol: "£",
    numericCode: 826,
    aliases: ["GG", "Guernsey"],
  },
  {
    iso: "GH",
    name: "Ghana",
    currency_code: "GHS",
    symbol: "GH₵",
    numericCode: 936,
    aliases: ["GH", "Ghana", "Republic of Ghana"],
  },
  {
    iso: "GI",
    name: "Gibraltar",
    currency_code: "GIP",
    symbol: "GIP",
    numericCode: 292,
    aliases: ["GI", "Gibraltar"],
  },
  {
    iso: "GL",
    name: "Greenland",
    currency_code: "DKK",
    symbol: "Dkr",
    numericCode: 208,
    aliases: ["GL", "Greenland", "Kalaallit Nunaat"],
  },
  {
    iso: "GM",
    name: "Gambia",
    currency_code: "GMD",
    symbol: "GMD",
    numericCode: 270,
    aliases: ["GM", "Gambia", "Republic of The Gambia"],
  },
  {
    iso: "GN",
    name: "Guinea",
    currency_code: "GNF",
    symbol: "FG",
    numericCode: 324,
    aliases: ["GN", "Guinea", "Republic of Guinea"],
  },
  {
    iso: "GP",
    name: "Guadeloupe",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["GP", "Guadeloupe"],
  },
  {
    iso: "GQ",
    name: "Equatorial Guinea",
    currency_code: "XAF",
    symbol: "FCFA",
    numericCode: 950,
    aliases: ["GQ", "Equatorial Guinea", "Republic of Equatorial Guinea"],
  },
  {
    iso: "GR",
    name: "Greece",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d/M/yyyy",
    numericCode: 978,
    aliases: ["GR", "Greece", "Hellenic Republic"],
  },
  {
    iso: "GS",
    name: "South Georgia and the South Sandwich Islands",
    currency_code: "GBP",
    symbol: "£",
    numericCode: 826,
    aliases: ["GS", "South Georgia and the South Sandwich Islands"],
  },
  {
    iso: "GT",
    name: "Guatemala",
    currency_code: "GTQ",
    symbol: "GTQ",
    dateFormat: "d/MM/yyyy",
    numericCode: 320,
    aliases: ["GT", "Guatemala", "Republic of Guatemala"],
  },
  {
    iso: "GU",
    name: "Guam",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["GU", "Guam"],
  },
  {
    iso: "GW",
    name: "Guinea-Bissau",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: [
      "GW",
      "Guinea-Bissau",
      "Guinea Bissau",
      "Republic of Guinea-Bissau",
    ],
  },
  {
    iso: "GY",
    name: "Guyana",
    currency_code: "GYD",
    symbol: "GYD",
    numericCode: 328,
    aliases: ["GY", "Guyana", "Co-operative Republic of Guyana"],
  },
  {
    iso: "HK",
    name: "Hong Kong",
    currency_code: "HKD",
    symbol: "HK$",
    dateFormat: "yyyy年M月d日",
    numericCode: 344,
    aliases: [
      "HK",
      "Hong Kong",
      "Hong Kong Special Administrative Region of China",
      "Hong Kong Special Administrative Region of the People's Republic of China",
    ],
  },
  {
    iso: "HM",
    name: "Heard Island and McDonald Islands",
    currency_code: "AUD",
    symbol: "AU$",
    numericCode: 36,
    aliases: ["HM", "Heard Island and McDonald Islands"],
  },
  {
    iso: "HN",
    name: "Honduras",
    currency_code: "HNL",
    symbol: "HNL",
    dateFormat: "MM-dd-yyyy",
    numericCode: 340,
    aliases: ["HN", "Honduras", "Republic of Honduras"],
  },
  {
    iso: "HR",
    name: "Croatia",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd.MM.yyyy.",
    numericCode: 978,
    aliases: ["HR", "Croatia", "Republic of Croatia"],
  },
  {
    iso: "HT",
    name: "Haiti",
    currency_code: "HTG",
    symbol: "HTG",
    numericCode: 332,
    aliases: ["HT", "Haiti", "Republic of Haiti"],
  },
  {
    iso: "HU",
    name: "Hungary",
    currency_code: "HUF",
    symbol: "Ft",
    dateFormat: "yyyy.MM.dd.",
    numericCode: 348,
    aliases: ["HU", "Hungary", "Republic of Hungary"],
  },
  {
    iso: "ID",
    name: "Indonesia",
    currency_code: "IDR",
    symbol: "Rp",
    dateFormat: "dd/MM/yyyy",
    numericCode: 360,
    aliases: ["ID", "Indonesia", "Republic of Indonesia"],
  },
  {
    iso: "IE",
    name: "Ireland",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd/MM/yyyy",
    numericCode: 978,
    aliases: ["IE", "Ireland", "Republic of Ireland"],
  },
  {
    iso: "IL",
    name: "Israel",
    currency_code: "ILS",
    symbol: "₪",
    dateFormat: "dd/MM/yyyy",
    numericCode: 376,
    aliases: ["IL", "Israel", "State of Israel"],
  },
  {
    iso: "IM",
    name: "Isle of Man",
    currency_code: "GBP",
    symbol: "£",
    numericCode: 826,
    aliases: ["IM", "Isle of Man"],
  },
  {
    iso: "IN",
    name: "India",
    currency_code: "INR",
    symbol: "₹",
    dateFormat: "d/M/yyyy",
    numericCode: 356,
    aliases: ["IN", "India", "Republic of India", "Bharat"],
  },
  {
    iso: "IO",
    name: "British Indian Ocean Territory",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["IO", "British Indian Ocean Territory"],
  },
  {
    iso: "IQ",
    name: "Iraq",
    currency_code: "IQD",
    symbol: "IQD",
    dateFormat: "dd/MM/yyyy",
    numericCode: 368,
    aliases: ["IQ", "Iraq", "Republic of Iraq"],
  },
  {
    iso: "IR",
    name: "Iran",
    currency_code: "IRR",
    symbol: "IRR",
    numericCode: 364,
    aliases: ["IR", "Iran", "Islamic Republic of Iran"],
  },
  {
    iso: "IS",
    name: "Iceland",
    currency_code: "ISK",
    symbol: "Ikr",
    dateFormat: "d.M.yyyy",
    numericCode: 352,
    aliases: ["IS", "Iceland", "Republic of Iceland"],
  },
  {
    iso: "IT",
    name: "Italy",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd/MM/yyyy",
    numericCode: 978,
    aliases: ["IT", "Italy", "Italian Republic"],
  },
  {
    iso: "JE",
    name: "Jersey",
    currency_code: "GBP",
    symbol: "£",
    numericCode: 826,
    aliases: ["JE", "Jersey"],
  },
  {
    iso: "JM",
    name: "Jamaica",
    currency_code: "JMD",
    symbol: "J$",
    numericCode: 388,
    aliases: ["JM", "Jamaica"],
  },
  {
    iso: "JO",
    name: "Jordan",
    currency_code: "JOD",
    symbol: "JD",
    dateFormat: "dd/MM/yyyy",
    numericCode: 400,
    aliases: ["JO", "Jordan", "Hashemite Kingdom of Jordan"],
  },
  {
    iso: "JP",
    name: "Japan",
    currency_code: "JPY",
    symbol: "¥",
    dateFormat: "H24.MM.dd",
    numericCode: 392,
    aliases: ["JP", "Japan"],
  },
  {
    iso: "KE",
    name: "Kenya",
    currency_code: "KES",
    symbol: "Ksh",
    numericCode: 404,
    aliases: ["KE", "Kenya", "Republic of Kenya"],
  },
  {
    iso: "KG",
    name: "Kyrgyzstan",
    currency_code: "KGS",
    symbol: "KGS",
    numericCode: 417,
    aliases: ["KG", "Kyrgyzstan", "Kyrgyz Republic"],
  },
  {
    iso: "KH",
    name: "Cambodia",
    currency_code: "KHR",
    symbol: "KHR",
    numericCode: 116,
    aliases: ["KH", "Cambodia", "Kingdom of Cambodia"],
  },
  {
    iso: "KI",
    name: "Kiribati",
    currency_code: "AUD",
    symbol: "AU$",
    numericCode: 36,
    aliases: ["KI", "Kiribati", "Republic of Kiribati"],
  },
  {
    iso: "KM",
    name: "Comoros",
    currency_code: "KMF",
    symbol: "CF",
    numericCode: 174,
    aliases: ["KM", "Comoros", "Union of the Comoros"],
  },
  {
    iso: "KN",
    name: "Saint Kitts and Nevis",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["KN", "Saint Kitts and Nevis"],
  },
  {
    iso: "KP",
    name: "North Korea",
    currency_code: "KPW",
    symbol: "KPW",
    numericCode: 408,
    aliases: [
      "KP",
      "North Korea",
      "Democratic People's Republic of Korea",
      "DPRK",
    ],
  },
  {
    iso: "KR",
    name: "South Korea",
    currency_code: "KRW",
    symbol: "₩",
    dateFormat: "yyyy. M. d",
    numericCode: 410,
    aliases: ["KR", "South Korea", "Republic of Korea", "ROK"],
  },
  {
    iso: "KW",
    name: "Kuwait",
    currency_code: "KWD",
    symbol: "KD",
    dateFormat: "dd/MM/yyyy",
    numericCode: 414,
    aliases: ["KW", "Kuwait", "State of Kuwait"],
  },
  {
    iso: "KY",
    name: "Cayman Islands",
    currency_code: "KYD",
    symbol: "KYD",
    numericCode: 136,
    aliases: ["KY", "Cayman Islands"],
  },
  {
    iso: "KZ",
    name: "Kazakhstan",
    currency_code: "KZT",
    symbol: "KZT",
    numericCode: 398,
    aliases: ["KZ", "Kazakhstan", "Republic of Kazakhstan"],
  },
  {
    iso: "LA",
    name: "Laos",
    currency_code: "LAK",
    symbol: "LAK",
    numericCode: 418,
    aliases: ["LA", "Laos", "Lao People's Democratic Republic"],
  },
  {
    iso: "LB",
    name: "Lebanon",
    currency_code: "LBP",
    symbol: "LB£",
    dateFormat: "dd/MM/yyyy",
    numericCode: 422,
    aliases: ["LB", "Lebanon", "Lebanese Republic"],
  },
  {
    iso: "LC",
    name: "Saint Lucia",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["LC", "Saint Lucia"],
  },
  {
    iso: "LI",
    name: "Liechtenstein",
    currency_code: "CHF",
    symbol: "CHF",
    numericCode: 756,
    aliases: ["LI", "Liechtenstein", "Principality of Liechtenstein"],
  },
  {
    iso: "LK",
    name: "Sri Lanka",
    currency_code: "LKR",
    symbol: "SLRs",
    numericCode: 144,
    aliases: [
      "LK",
      "Sri Lanka",
      "Democratic Socialist Republic of Sri Lanka",
      "Ceylon",
    ],
  },
  {
    iso: "LR",
    name: "Liberia",
    currency_code: "LRD",
    symbol: "LRD",
    numericCode: 430,
    aliases: ["LR", "Liberia", "Republic of Liberia"],
  },
  {
    iso: "LS",
    name: "Lesotho",
    currency_code: "LSL",
    symbol: "LSL",
    numericCode: 426,
    aliases: ["LS", "Lesotho", "Kingdom of Lesotho"],
  },
  {
    iso: "LT",
    name: "Lithuania",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "yyyy.M.d",
    numericCode: 978,
    aliases: ["LT", "Lithuania", "Republic of Lithuania"],
  },
  {
    iso: "LU",
    name: "Luxembourg",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd.MM.yyyy",
    numericCode: 978,
    aliases: ["LU", "Luxembourg", "Grand Duchy of Luxembourg"],
  },
  {
    iso: "LV",
    name: "Latvia",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "yyyy.d.M",
    numericCode: 978,
    aliases: ["LV", "Latvia", "Republic of Latvia"],
  },
  {
    iso: "LY",
    name: "Libya",
    currency_code: "LYD",
    symbol: "LD",
    dateFormat: "dd/MM/yyyy",
    numericCode: 434,
    aliases: ["LY", "Libya", "State of Libya"],
  },
  {
    iso: "MA",
    name: "Morocco",
    currency_code: "MAD",
    symbol: "MAD",
    dateFormat: "dd/MM/yyyy",
    numericCode: 504,
    aliases: ["MA", "Morocco", "Kingdom of Morocco"],
  },
  {
    iso: "MC",
    name: "Monaco",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["MC", "Monaco", "Principality of Monaco"],
  },
  {
    iso: "MD",
    name: "Moldova",
    currency_code: "MDL",
    symbol: "MDL",
    numericCode: 498,
    aliases: ["MD", "Moldova", "Republic of Moldova"],
  },
  {
    iso: "ME",
    name: "Montenegro",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d.M.yyyy.",
    numericCode: 978,
    aliases: ["ME", "Montenegro"],
  },
  {
    iso: "MF",
    name: "Saint Martin",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["MF", "Saint Martin"],
  },
  {
    iso: "MG",
    name: "Madagascar",
    currency_code: "MGA",
    symbol: "MGA",
    numericCode: 969,
    aliases: ["MG", "Madagascar", "Republic of Madagascar"],
  },
  {
    iso: "MH",
    name: "Marshall Islands",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["MH", "Marshall Islands", "Republic of the Marshall Islands"],
  },
  {
    iso: "MK",
    name: "Macedonia",
    currency_code: "MKD",
    symbol: "MKD",
    dateFormat: "d.M.yyyy",
    numericCode: 807,
    aliases: ["MK", "Macedonia", "Republic of Macedonia"],
  },
  {
    iso: "ML",
    name: "Mali",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: ["ML", "Mali", "Republic of Mali"],
  },
  {
    iso: "MM",
    name: "Myanmar",
    currency_code: "MMK",
    symbol: "MMK",
    numericCode: 104,
    aliases: ["MM", "Myanmar", "Republic of the Union of Myanmar"],
  },
  {
    iso: "MN",
    name: "Mongolia",
    currency_code: "MNT",
    symbol: "MNT",
    numericCode: 496,
    aliases: ["MN", "Mongolia"],
  },
  {
    iso: "MO",
    name: "Macao",
    currency_code: "MOP",
    symbol: "MOP$",
    numericCode: 446,
    aliases: ["MO", "Macao", "Macao Special Administrative Region of China"],
  },
  {
    iso: "MP",
    name: "Northern Mariana Islands",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["MP", "Northern Mariana Islands"],
  },
  {
    iso: "MQ",
    name: "Martinique",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["MQ", "Martinique"],
  },
  {
    iso: "MR",
    name: "Mauritania",
    currency_code: "MRU",
    symbol: "MRU",
    numericCode: 929,
    aliases: ["MR", "Mauritania", "Islamic Republic of Mauritania"],
  },
  {
    iso: "MS",
    name: "Montserrat",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["MS", "Montserrat"],
  },
  {
    iso: "MT",
    name: "Malta",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd/MM/yyyy",
    numericCode: 978,
    aliases: ["MT", "Malta", "Republic of Malta"],
  },
  {
    iso: "MU",
    name: "Mauritius",
    currency_code: "MUR",
    symbol: "MURs",
    numericCode: 480,
    aliases: ["MU", "Mauritius", "Republic of Mauritius"],
  },
  {
    iso: "MV",
    name: "Maldives",
    currency_code: "MVR",
    symbol: "MVR",
    numericCode: 462,
    aliases: ["MV", "Maldives", "Republic of Maldives"],
  },
  {
    iso: "MW",
    name: "Malawi",
    currency_code: "MWK",
    symbol: "MWK",
    numericCode: 454,
    aliases: ["MW", "Malawi", "Republic of Malawi"],
  },
  {
    iso: "MX",
    name: "Mexico",
    currency_code: "MXN",
    symbol: "MX$",
    dateFormat: "d/MM/yyyy",
    numericCode: 484,
    aliases: ["MX", "Mexico", "United Mexican States"],
  },
  {
    iso: "MY",
    name: "Malaysia",
    currency_code: "MYR",
    symbol: "RM",
    dateFormat: "dd/MM/yyyy",
    numericCode: 458,
    aliases: ["MY", "Malaysia"],
  },
  {
    iso: "MZ",
    name: "Mozambique",
    currency_code: "MZN",
    symbol: "MTn",
    numericCode: 943,
    aliases: ["MZ", "Mozambique", "Republic of Mozambique"],
  },
  {
    iso: "NA",
    name: "Namibia",
    currency_code: "NAD",
    symbol: "N$",
    numericCode: 516,
    aliases: ["NA", "Namibia", "Republic of Namibia"],
  },
  {
    iso: "NC",
    name: "New Caledonia",
    currency_code: "XPF",
    symbol: "XPF",
    numericCode: 953,
    aliases: ["NC", "New Caledonia"],
  },
  {
    iso: "NE",
    name: "Niger",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: ["NE", "Niger", "Republic of the Niger"],
  },
  {
    iso: "NF",
    name: "Norfolk Island",
    currency_code: "AUD",
    symbol: "AU$",
    numericCode: 36,
    aliases: ["NF", "Norfolk Island"],
  },
  {
    iso: "NG",
    name: "Nigeria",
    currency_code: "NGN",
    symbol: "₦",
    numericCode: 566,
    aliases: ["NG", "Nigeria", "Federal Republic of Nigeria"],
  },
  {
    iso: "NI",
    name: "Nicaragua",
    currency_code: "NIO",
    symbol: "C$",
    dateFormat: "MM-dd-yyyy",
    numericCode: 558,
    aliases: ["NI", "Nicaragua", "Republic of Nicaragua"],
  },
  {
    iso: "NL",
    name: "Netherlands",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d-M-yyyy",
    numericCode: 978,
    aliases: ["NL", "Netherlands", "Kingdom of the Netherlands"],
  },
  {
    iso: "NO",
    name: "Norway",
    currency_code: "NOK",
    symbol: "Nkr",
    dateFormat: "dd.MM.yyyy",
    numericCode: 578,
    aliases: ["NO", "Norway", "Kingdom of Norway"],
  },
  {
    iso: "NP",
    name: "Nepal",
    currency_code: "NPR",
    symbol: "NPRs",
    numericCode: 524,
    aliases: ["NP", "Nepal", "Federal Democratic Republic of Nepal"],
  },
  {
    iso: "NR",
    name: "Nauru",
    currency_code: "AUD",
    symbol: "AU$",
    numericCode: 36,
    aliases: ["NR", "Nauru", "Republic of Nauru"],
  },
  {
    iso: "NU",
    name: "Niue",
    currency_code: "NZD",
    symbol: "NZ$",
    numericCode: 554,
    aliases: ["NU", "Niue"],
  },
  {
    iso: "NZ",
    name: "New Zealand",
    currency_code: "NZD",
    symbol: "NZ$",
    dateFormat: "d/MM/yyyy",
    numericCode: 554,
    aliases: ["NZ", "New Zealand"],
  },
  {
    iso: "OM",
    name: "Oman",
    currency_code: "OMR",
    symbol: "OMR",
    dateFormat: "dd/MM/yyyy",
    numericCode: 512,
    aliases: ["OM", "Oman", "Sultanate of Oman"],
  },
  {
    iso: "PA",
    name: "Panama",
    currency_code: "PAB",
    symbol: "B/.",
    dateFormat: "MM/dd/yyyy",
    numericCode: 590,
    aliases: ["PA", "Panama", "Republic of Panama"],
  },
  {
    iso: "PE",
    name: "Peru",
    currency_code: "PEN",
    symbol: "S/.",
    dateFormat: "dd/MM/yyyy",
    numericCode: 604,
    aliases: ["PE", "Peru", "Republic of Peru"],
  },
  {
    iso: "PF",
    name: "French Polynesia",
    currency_code: "XPF",
    symbol: "XPF",
    numericCode: 953,
    aliases: ["PF", "French Polynesia"],
  },
  {
    iso: "PG",
    name: "Papua New Guinea",
    currency_code: "PGK",
    symbol: "PGK",
    numericCode: 598,
    aliases: [
      "PG",
      "Papua New Guinea",
      "Independent State of Papua New Guinea",
    ],
  },
  {
    iso: "PH",
    name: "Philippines",
    currency_code: "PHP",
    symbol: "₱",
    dateFormat: "M/d/yyyy",
    numericCode: 608,
    aliases: ["PH", "Philippines", "Republic of the Philippines"],
  },
  {
    iso: "PK",
    name: "Pakistan",
    currency_code: "PKR",
    symbol: "PKRs",
    numericCode: 586,
    aliases: ["PK", "Pakistan", "Islamic Republic of Pakistan"],
  },
  {
    iso: "PL",
    name: "Poland",
    currency_code: "PLN",
    symbol: "zł",
    dateFormat: "dd.MM.yyyy",
    numericCode: 985,
    aliases: ["PL", "Poland", "Republic of Poland"],
  },
  {
    iso: "PM",
    name: "Saint Pierre and Miquelon",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["PM", "Saint Pierre and Miquelon"],
  },
  {
    iso: "PN",
    name: "Pitcairn",
    currency_code: "NZD",
    symbol: "NZ$",
    numericCode: 554,
    aliases: ["PN", "Pitcairn"],
  },
  {
    iso: "PR",
    name: "Puerto Rico",
    currency_code: "USD",
    symbol: "$",
    dateFormat: "MM-dd-yyyy",
    numericCode: 840,
    aliases: ["PR", "Puerto Rico"],
  },
  {
    iso: "PS",
    name: "Palestinian Territory",
    currency_code: "ILS",
    symbol: "₪",
    numericCode: 376,
    aliases: ["PS", "Palestinian Territory", "Occupied Palestinian Territory"],
  },
  {
    iso: "PT",
    name: "Portugal",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "dd-MM-yyyy",
    numericCode: 978,
    aliases: ["PT", "Portugal", "Portuguese Republic"],
  },
  {
    iso: "PW",
    name: "Palau",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["PW", "Palau", "Republic of Palau"],
  },
  {
    iso: "PY",
    name: "Paraguay",
    currency_code: "PYG",
    symbol: "₲",
    dateFormat: "dd/MM/yyyy",
    numericCode: 600,
    aliases: ["PY", "Paraguay", "Republic of Paraguay"],
  },
  {
    iso: "QA",
    name: "Qatar",
    currency_code: "QAR",
    symbol: "QR",
    dateFormat: "dd/MM/yyyy",
    numericCode: 634,
    aliases: ["QA", "Qatar", "State of Qatar"],
  },
  {
    iso: "RE",
    name: "Reunion",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["RE", "Reunion"],
  },
  {
    iso: "RO",
    name: "Romania",
    currency_code: "RON",
    symbol: "RON",
    dateFormat: "dd.MM.yyyy",
    numericCode: 946,
    aliases: ["RO", "Romania"],
  },
  {
    iso: "RS",
    name: "Serbia",
    currency_code: "RSD",
    symbol: "din.",
    dateFormat: "d.M.yyyy.",
    numericCode: 941,
    aliases: ["RS", "Serbia", "Republic of Serbia"],
  },
  {
    iso: "RU",
    name: "Russia",
    currency_code: "RUB",
    symbol: "RUB",
    dateFormat: "dd.MM.yyyy",
    numericCode: 643,
    aliases: ["RU", "Russia", "Russian Federation"],
  },
  {
    iso: "RW",
    name: "Rwanda",
    currency_code: "RWF",
    symbol: "RWF",
    numericCode: 646,
    aliases: ["RW", "Rwanda", "Republic of Rwanda"],
  },
  {
    iso: "SA",
    name: "Saudi Arabia",
    currency_code: "SAR",
    symbol: "SR",
    dateFormat: "dd/MM/yyyy",
    numericCode: 682,
    aliases: ["SA", "Saudi Arabia", "Kingdom of Saudi Arabia"],
  },
  {
    iso: "SB",
    name: "Solomon Islands",
    currency_code: "SBD",
    symbol: "SBD",
    numericCode: 90,
    aliases: ["SB", "Solomon Islands"],
  },
  {
    iso: "SC",
    name: "Seychelles",
    currency_code: "SCR",
    symbol: "SCR",
    numericCode: 690,
    aliases: ["SC", "Seychelles", "Republic of Seychelles"],
  },
  {
    iso: "SD",
    name: "Sudan",
    currency_code: "SDG",
    symbol: "SDG",
    dateFormat: "dd/MM/yyyy",
    numericCode: 938,
    aliases: ["SD", "Sudan", "Republic of the Sudan"],
  },
  {
    iso: "SE",
    name: "Sweden",
    currency_code: "SEK",
    symbol: "Skr",
    dateFormat: "yyyy-MM-dd",
    numericCode: 752,
    aliases: ["SE", "Sweden", "Kingdom of Sweden"],
  },
  {
    iso: "SG",
    name: "Singapore",
    currency_code: "SGD",
    symbol: "S$",
    dateFormat: "M/d/yyyy",
    numericCode: 702,
    aliases: ["SG", "Singapore", "Republic of Singapore"],
  },
  {
    iso: "SH",
    name: "Saint Helena",
    currency_code: "SHP",
    symbol: "SHP",
    numericCode: 654,
    aliases: ["SH", "Saint Helena"],
  },
  {
    iso: "SI",
    name: "Slovenia",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d.M.yyyy",
    numericCode: 978,
    aliases: ["SI", "Slovenia", "Republic of Slovenia"],
  },
  {
    iso: "SJ",
    name: "Svalbard and Jan Mayen",
    currency_code: "NOK",
    symbol: "Nkr",
    numericCode: 578,
    aliases: ["SJ", "Svalbard and Jan Mayen"],
  },
  {
    iso: "SK",
    name: "Slovakia",
    currency_code: "EUR",
    symbol: "€",
    dateFormat: "d.M.yyyy",
    numericCode: 978,
    aliases: ["SK", "Slovakia", "Slovak Republic"],
  },
  {
    iso: "SL",
    name: "Sierra Leone",
    currency_code: "SLL",
    symbol: "SLL",
    numericCode: 694,
    aliases: ["SL", "Sierra Leone", "Republic of Sierra Leone"],
  },
  {
    iso: "SM",
    name: "San Marino",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["SM", "San Marino", "Republic of San Marino"],
  },
  {
    iso: "SN",
    name: "Senegal",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: ["SN", "Senegal", "Republic of Senegal"],
  },
  {
    iso: "SO",
    name: "Somalia",
    currency_code: "SOS",
    symbol: "Ssh",
    numericCode: 706,
    aliases: ["SO", "Somalia", "Federal Republic of Somalia"],
  },
  {
    iso: "SR",
    name: "Suriname",
    currency_code: "SRD",
    symbol: "SRD",
    numericCode: 968,
    aliases: ["SR", "Suriname", "Republic of Suriname"],
  },
  {
    iso: "SS",
    name: "South Sudan",
    currency_code: "SSP",
    symbol: "SSP",
    numericCode: 728,
    aliases: ["SS", "South Sudan", "Republic of South Sudan"],
  },
  {
    iso: "ST",
    name: "Sao Tome and Principe",
    currency_code: "STD",
    symbol: "STD",
    numericCode: 678,
    aliases: [
      "ST",
      "Sao Tome and Principe",
      "Democratic Republic of Sao Tome and Principe",
    ],
  },
  {
    iso: "SV",
    name: "El Salvador",
    currency_code: "USD",
    symbol: "$",
    dateFormat: "MM-dd-yyyy",
    numericCode: 840,
    aliases: ["SV", "El Salvador", "Republic of El Salvador"],
  },
  {
    iso: "SX",
    name: "Sint Maarten",
    currency_code: "ANG",
    symbol: "ANG",
    numericCode: 532,
    aliases: ["SX", "Sint Maarten"],
  },
  {
    iso: "SY",
    name: "Syria",
    currency_code: "SYP",
    symbol: "SY£",
    dateFormat: "dd/MM/yyyy",
    numericCode: 760,
    aliases: ["SY", "Syria", "Syrian Arab Republic"],
  },
  {
    iso: "SZ",
    name: "Swaziland",
    currency_code: "SZL",
    symbol: "SZL",
    numericCode: 748,
    aliases: ["SZ", "Swaziland", "Kingdom of Swaziland"],
  },
  {
    iso: "TC",
    name: "Turks and Caicos Islands",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["TC", "Turks and Caicos Islands"],
  },
  {
    iso: "TD",
    name: "Chad",
    currency_code: "XAF",
    symbol: "FCFA",
    numericCode: 950,
    aliases: ["TD", "Chad", "Republic of Chad"],
  },
  {
    iso: "TF",
    name: "French Southern Territories",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["TF", "French Southern Territories"],
  },
  {
    iso: "TG",
    name: "Togo",
    currency_code: "XOF",
    symbol: "CFA",
    numericCode: 952,
    aliases: ["TG", "Togo", "Togolese Republic"],
  },
  {
    iso: "TH",
    name: "Thailand",
    currency_code: "THB",
    symbol: "฿",
    dateFormat: "๓/๖/๒๕๕๕",
    numericCode: 764,
    aliases: ["TH", "Thailand", "Kingdom of Thailand"],
  },
  {
    iso: "TJ",
    name: "Tajikistan",
    currency_code: "TJS",
    symbol: "TJS",
    numericCode: 972,
    aliases: ["TJ", "Tajikistan", "Republic of Tajikistan"],
  },
  {
    iso: "TK",
    name: "Tokelau",
    currency_code: "NZD",
    symbol: "NZ$",
    numericCode: 554,
    aliases: ["TK", "Tokelau"],
  },
  {
    iso: "TL",
    name: "East Timor",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["TL", "East Timor", "Democratic Republic of Timor-Leste"],
  },
  {
    iso: "TM",
    name: "Turkmenistan",
    currency_code: "TMT",
    symbol: "TMT",
    numericCode: 934,
    aliases: ["TM", "Turkmenistan"],
  },
  {
    iso: "TN",
    name: "Tunisia",
    currency_code: "TND",
    symbol: "DT",
    dateFormat: "dd/MM/yyyy",
    numericCode: 788,
    aliases: ["TN", "Tunisia", "Republic of Tunisia"],
  },
  {
    iso: "TO",
    name: "Tonga",
    currency_code: "TOP",
    symbol: "T$",
    numericCode: 776,
    aliases: ["TO", "Tonga", "Kingdom of Tonga"],
  },
  {
    iso: "TR",
    name: "Turkey",
    currency_code: "TRY",
    symbol: "₺",
    dateFormat: "dd.MM.yyyy",
    numericCode: 949,
    aliases: ["TR", "Turkey", "Republic of Turkey"],
  },
  {
    iso: "TT",
    name: "Trinidad and Tobago",
    currency_code: "TTD",
    symbol: "TT$",
    numericCode: 780,
    aliases: ["TT", "Trinidad and Tobago", "Republic of Trinidad and Tobago"],
  },
  {
    iso: "TV",
    name: "Tuvalu",
    currency_code: "AUD",
    symbol: "AU$",
    numericCode: 36,
    aliases: ["TV", "Tuvalu"],
  },
  {
    iso: "TW",
    name: "Taiwan",
    currency_code: "TWD",
    symbol: "NT$",
    dateFormat: "yyyy/M/d",
    numericCode: 901,
    aliases: ["TW", "Taiwan", "Republic of China"],
  },
  {
    iso: "TZ",
    name: "Tanzania",
    currency_code: "TZS",
    symbol: "TSh",
    numericCode: 834,
    aliases: ["TZ", "Tanzania", "United Republic of Tanzania"],
  },
  {
    iso: "UA",
    name: "Ukraine",
    currency_code: "UAH",
    symbol: "₴",
    dateFormat: "dd.MM.yyyy",
    numericCode: 980,
    aliases: ["UA", "Ukraine"],
  },
  {
    iso: "UG",
    name: "Uganda",
    currency_code: "UGX",
    symbol: "USh",
    numericCode: 800,
    aliases: ["UG", "Uganda", "Republic of Uganda"],
  },
  {
    iso: "UM",
    name: "United States Minor Outlying Islands",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["UM", "United States Minor Outlying Islands"],
  },
  {
    iso: "US",
    name: "United States of America",
    currency_code: "USD",
    symbol: "$",
    dateFormat: "M/d/yyyy",
    numericCode: 840,
    aliases: [
      "US",
      "United States of America",
      "United States",
      "USA",
      "U.S.",
      "America",
      "U.S.A.",
    ],
  },
  {
    iso: "UY",
    name: "Uruguay",
    currency_code: "UYU",
    symbol: "$U",
    dateFormat: "dd/MM/yyyy",
    numericCode: 858,
    aliases: ["UY", "Uruguay", "Oriental Republic of Uruguay"],
  },
  {
    iso: "UZ",
    name: "Uzbekistan",
    currency_code: "UZS",
    symbol: "UZS",
    numericCode: 860,
    aliases: ["UZ", "Uzbekistan", "Republic of Uzbekistan"],
  },
  {
    iso: "VA",
    name: "Vatican",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["VA", "Vatican", "Vatican City State"],
  },
  {
    iso: "VC",
    name: "Saint Vincent and the Grenadines",
    currency_code: "XCD",
    symbol: "XCD",
    numericCode: 951,
    aliases: ["VC", "Saint Vincent and the Grenadines"],
  },
  {
    iso: "VE",
    name: "Venezuela",
    currency_code: "VEF",
    symbol: "Bs.F.",
    dateFormat: "dd/MM/yyyy",
    numericCode: 937,
    aliases: ["VE", "Venezuela", "Bolivarian Republic of Venezuela"],
  },
  {
    iso: "VG",
    name: "British Virgin Islands",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["VG", "British Virgin Islands"],
  },
  {
    iso: "VI",
    name: "U.S. Virgin Islands",
    currency_code: "USD",
    symbol: "$",
    numericCode: 840,
    aliases: ["VI", "U.S. Virgin Islands"],
  },
  {
    iso: "VN",
    name: "Vietnam",
    currency_code: "VND",
    symbol: "₫",
    dateFormat: "dd/MM/yyyy",
    numericCode: 704,
    aliases: ["VN", "Vietnam", "Social Republic of Vietnam"],
  },
  {
    iso: "VU",
    name: "Vanuatu",
    currency_code: "VUV",
    symbol: "VUV",
    numericCode: 548,
    aliases: ["VU", "Vanuatu", "Republic of Vanuatu"],
  },
  {
    iso: "WF",
    name: "Wallis and Futuna",
    currency_code: "XPF",
    symbol: "XPF",
    numericCode: 953,
    aliases: ["WF", "Wallis and Futuna"],
  },
  {
    iso: "WS",
    name: "Samoa",
    currency_code: "WST",
    symbol: "WST",
    numericCode: 882,
    aliases: ["WS", "Samoa", "Independent State of Samoa"],
  },
  {
    iso: "XK",
    name: "Kosovo",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["XK", "Kosovo", "Republic of Kosovo"],
  },
  {
    iso: "YE",
    name: "Yemen",
    currency_code: "YER",
    symbol: "YR",
    dateFormat: "dd/MM/yyyy",
    numericCode: 886,
    aliases: ["YE", "Yemen", "Republic of Yemen"],
  },
  {
    iso: "YT",
    name: "Mayotte",
    currency_code: "EUR",
    symbol: "€",
    numericCode: 978,
    aliases: ["YT", "Mayotte"],
  },
  {
    iso: "ZA",
    name: "South Africa",
    currency_code: "ZAR",
    symbol: "R",
    dateFormat: "yyyy/MM/dd",
    numericCode: 710,
    aliases: ["ZA", "South Africa", "Republic of South Africa"],
  },
  {
    iso: "ZM",
    name: "Zambia",
    currency_code: "ZMW",
    symbol: "ZK",
    numericCode: 967,
    aliases: ["ZM", "Zambia", "Republic of Zambia"],
  },
  {
    iso: "ZW",
    name: "Zimbabwe",
    currency_code: "ZWL",
    symbol: "ZWL",
    numericCode: 932,
    aliases: ["ZW", "Zimbabwe", "Republic of Zimbabwe"],
  },
];
